version: 2
jobs:
  build:
    working_directory: ~/gasstation-express-oracle
    docker:
      - image: circleci/python:3.5.3
    steps:
      - checkout
      - run:
          name: Create .pypirc
          command: chmod +x .circleci/pypirc.sh && .circleci/pypirc.sh
      - run:
          name: Install requirements
          command: |
            python3 -m venv env
            source ./env/bin/activate
            pip3 install -r requirements.txt
      - store_artifacts:
          path: ./reports/
          destination: reports

  whitesource:
    working_directory: ~/gasstation-express-oracle
    docker:
      - image: circleci/openjdk:8-node-browsers
    steps:
      - checkout
      - attach_workspace:
          at: ~/gasstation-express-oracle/workspace
      - run :
          name: Setup WhiteSource
          command: curl -LJO https://github.com/whitesource/fs-agent-distribution/raw/master/standAlone/wss_agent.sh
      - run:
          name: execute whitesource
          command: |
            cd .whitesource/
            chmod +x wss_agent.sh && ./wss_agent.sh -apiKey $WHITESOURCE_API_KEY -c ./whitesource-fs-agent.config  -project gasstation-express-oracle -f files.list

  package-publish-qa:
    working_directory: ~/gasstation-express-oracle
    docker:
      - image: circleci/python:3.5.3
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: pip install awscli --upgrade --user
      - run:
          name: Create .pypirc and append CircleCI build number as version
          command: |
            chmod +x .circleci/pypirc.sh && .circleci/pypirc.sh
            touch version.py
            echo "__version__ = '0.1.$CIRCLE_BUILD_NUM-qa'" > version.py
      - run:
          name: Install requirements
          command: |
            python3 -m venv env
            source ./env/bin/activate
            pip3 install -r requirements.txt
      - run:
          name: Git config
          command: |
            git config user.email "devops@pillar.io"
            git config user.name "Issabot"
      - run:
          name: Publish Package to Artifactory
          command: |
            python3 setup.py sdist upload -r local
            chmod +x .circleci/announceRelease.sh && .circleci/announceRelease.sh "gassstation-express-oracle-qa" "gassstation-express-oracle-qa:$CIRCLE_BUILD_NUM"
      - run:
          name: Push txt file to S3 bucket
          command: |
            touch gasstation-express-oracle.txt
            echo "gasstation-express-oracle@0.1.$CIRCLE_BUILD_NUM-qa" > gasstation-express-oracle.txt
            export AWS_ACCESS_KEY_ID=$STAGING_AWS_ACCESS_KEY_ID
            export AWS_SECRET_ACCESS_KEY=$STAGING_AWS_SECRET_ACCESS_KEY
            /home/circleci/.local/bin/aws s3 cp gasstation-express-oracle.txt $QA_RELEASE_BUCKET
      - run:
          name: Announce Deployment
          command: |
            chmod +x .circleci/announceDeployment.sh
            .circleci/announceDeployment.sh "gasstation-express-oracle" "QA" "$(cat ./gasstation-express-oracle.txt)"

  package-publish-prod:
    working_directory: ~/gasstation-express-oracle
    docker:
      - image: circleci/python:3.5.3
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: pip install awscli --upgrade --user
      - run:
          name: Create .pypirc and append CircleCI build number as version
          command: |
            chmod +x .circleci/pypirc.sh && .circleci/pypirc.sh
            touch version.py
            echo "__version__ = '0.1.$CIRCLE_BUILD_NUM'" > version.py
      - run:
          name: Install requirements
          command: |
            python3 -m venv env
            source ./env/bin/activate
            pip3 install -r requirements.txt
      - run:
          name: Git config
          command: |
            git config user.email "devops@pillar.io"
            git config user.name "Issabot"
      - run:
          name: Publish Package to Artifactory
          command: |
            python3 setup.py sdist upload -r local
            chmod +x .circleci/announceRelease.sh && .circleci/announceRelease.sh "gassstation-express-oracle" "gassstation-express-oracle:$CIRCLE_BUILD_NUM"
      - run:
          name: Push txt file to S3 bucket
          command: |
            touch gasstation-express-oracle.txt
            echo "gasstation-express-oracle@0.1.$CIRCLE_BUILD_NUM" > gasstation-express-oracle.txt
            export AWS_ACCESS_KEY_ID=$PRODUCTION_AWS_ACCESS_KEY_ID
            export AWS_SECRET_ACCESS_KEY=$PRODUCTION_AWS_SECRET_ACCESS_KEY
            /home/circleci/.local/bin/aws s3 cp gasstation-express-oracle.txt $PRODUCTION_RELEASE_BUCKET
      - run:
          name: Announce Deployment
          command: |
            chmod +x .circleci/announceDeployment.sh
            .circleci/announceDeployment.sh "gasstation-express-oracle" "Production" "$(cat ./gasstation-express-oracle.txt)"

workflows:
  version: 2
  test_and_publish:
    jobs:
      - build
      - package-publish-qa:
          requires:
             - build
          filters:
            branches:
              only:
                  - develop
      - package-publish-prod:
          requires:
             - build
          filters:
            branches:
              only:
                  - master
